### ISSUE TITLE
Sample data change on Registration page

### ISSUE THREAD

**Issue by datatalking** [luzdelsol668/twice_new#4]
The current words that are filled in the page that are prefilled as sample values need to be edited to a more pythonic version. I've attached a version of what shows up now vs what shows up for a new user signing up for Salesforce that I would like to mimic.

The location of the boxes and the words around them are fine, we need to change the wording inside so instead of AGOU Holding we should use 'Company Name' to borrow from SalesForce and so on down the line.

We should say "Your email address must be in the form of an email address" but the rest can be blank for salesforce adds instructions we don't need. Post a few versions here and we can speed this along.

Thanks for helping, the client liked your clean design!

Old Text Schema
<img width="606" alt="Screen Shot 2023-02-01 at 4 07 19 PM" src="https://user-images.githubusercontent.com/11813209/216197634-55bcf1c2-ec15-47fe-8920-b0b5919c9828.png">

New Text Schema
<img width="609" alt="Screen Shot 2023-02-01 at 4 09 54 PM" src="https://user-images.githubusercontent.com/11813209/216197645-7ba6009b-2edc-40d6-a26e-c52852e19983.png">

**Comment by luzdelsol668** [comment]
ok. I'll Patch it.
